### ISSUE TITLE
希望作者能继续完善这个项目

### ISSUE THREAD

**Issue by LaoshuBaby** [muruoxi2018/TTS#1]
在给跑团剧本的B站投稿加文本的时候，希望能合成出对应的语句，但是一共两万多句，不知如何是好，而能力太差以至于Aliyun的SDK完全看不懂。
然后阴差阳错之际找到了贵repo
（好东西！！）
所以如果有比赛项目的话，把比赛版本单独做一个branch，然后正常的版本作为master继续维护，不是也可以的吗
期待

**Comment by muruoxi2018** [comment]
语音合成的话，可以用一些第三方软件哦，比如，录音啦等。
阿里云的语音合成sdk我没看过，但我觉的讯飞的语音合成挺好的。
另外目前的精力集中在了Word插件开发上，其中一个功能是将文本转为语音。
但遗憾的是个人开发速度很慢，加上微软给的神仙开发文档，还不知道什么时候能做出来。


| |
慕若曦
慕若曦博客  - 
站长
13993481533@163.com
|
签名由网易邮箱大师定制
在2020年3月11日 18:09，快乐的老鼠宝宝<notifications@github.com> 写道：

在给跑团剧本的B站投稿加文本的时候，希望能合成出对应的语句，但是一共两万多句，不知如何是好，而能力太差以至于Aliyun的SDK完全看不懂。
然后阴差阳错之际找到了贵repo
（好东西！！）
所以如果有比赛项目的话，把比赛版本单独做一个branch，然后正常的版本作为master继续维护，不是也可以的吗
期待

**Comment by j1g5awi** [comment]
挺有缘的，发现了同样需求的跑团玩家。
我因为被讯飞的api折腾半天来github找现成的代码，顺手点进了这个repo。
顺便安利下一个正在开发的跑团视频生成工具：[Spiral111/auto_video](https://github.com/Spiral111/auto_video/tree/jigsaw)
目前正在增加在线音源的计划中，希望对你有帮助。
